on:
 push:
  branches: main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: checkout
     uses: actions/checkout@v3
   - name: dockerbuild
     run:  |
          docker build -t app:latest .
   
   - name: trivyrun
      uses: aquasecurity/trivy-action@0.30.0
      with: 
          image-ref: app:latest
